# This is a basic workflow to help you get started with Actions

name: glualint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "v2.0" ]
  pull_request:
    branches: [ "master", "v2.0" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: GLua Linter
        # You may pin to the exact commit or the version.
        # uses: TASSIA710/action-glua-lint@f78bb3f45cbf45a387b0cc720ed12c0cc7d3867d
        uses: TASSIA710/action-glua-lint@v1.1.4
        with:
          lint_shadowing: false
          lint_profanity: false
          lint_unusedParameters: false
          lint_unusedLoopVars: false
          failOnWarning: true

